# Generated by Django 4.1 on 2022-10-15 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='universities.city'),
        ),
        migrations.AlterField(
            model_name='university',
            name='courses_codes',
            field=models.ManyToManyField(related_name='universities', through='universities.Price', to='universities.coursecode'),
        ),
    ]
