# Generated by Django 4.1 on 2022-10-15 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0002_alter_university_city_alter_university_courses_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='course_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='universities.coursecode'),
        ),
    ]
